name: App Python para testar Github Actions

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v5  # Repositório correto com "actions"
      with:
        python-version: 3.8
    - name: Instala dependências
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Teste com pytest
      run: pytest
